---
- name: Get rustup_user home
  become: yes
  getent:
    database: passwd
    key: "{{ rustup_user }}"
    split: ":"

- name: set rustup user home
  set_fact:
    rustup_user_home: "{{ getent_passwd[rustup_user][4] }}"

- name: set rustup user shell
  set_fact:
    rustup_user_shell: "{{ getent_passwd[rustup_user][5] }}"

- name: Create temporary install directory
  tempfile:
    state: directory
    suffix: .install
  register: temp_install_dir
  changed_when: false

- name: Install RustUp
  shell: |
    set -o pipefail
    curl https://sh.rustup.rs -sSf | sh -s -- -y
  args:
    creates: "{{ rustup_user_home }}/.cargo/bin/rustup"
    executable: /bin/bash
  environment:
    TMPDIR: '{{ temp_install_dir.path }}'

- name: Install cargo crates
  shell: |
    set -o pipefail
    echo "{{ item }}"
    cargo install "{{ item }}"
  loop: "{{ rustup_cargo_crates }}"
  register: crate_install_result
  changed_when: "'Downloaded' in crate_install_result.stdout"
  args:
    creates: "{{ rustup_user_home }}/.cargo/bin/{{ item }}"
    executable: /bin/bash
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ rustup_user_home }}/.cargo/bin"
    TMPDIR: '{{ temp_install_dir.path }}'
  when:
    - rustup_cargo_crates is defined
  ignore_errors: True
