---
- name: show packages to be installed
  debug:
    msg: "{{ item }}"
  loop: "{{ common_packages }}"

- name: Add and remove Zypper repositories
  zypper_repository:
    repo: "{{ item }}"
    state: present
  loop: "{{ suse_repos }}"
  ignore_errors: true

- name: zypper refresh
  shell:
    cmd: "zypper --gpg-auto-import-keys ref"

- name: switch system packages to packman
  shell: 'zypper ar -cfp 90 http://ftp.gwdg.de/pub/linux/misc/packman/suse/openSUSE_Tumbleweed/ packman && zypper dup --from packman --allow-vendor-change -y'
  ignore_errors: true

- name: install packages with zypper
  zypper:
    name: "{{ common_packages + suse_packages }}"
    state: latest
  ignore_errors: true

- name: install patterns with zypper
  zypper:
    name: "{{ suse_patterns }}"
    type: pattern
    state: latest
  ignore_errors: true
