---
- name: create temporary install directory
  tempfile:
    state: directory
    suffix: .install
  register: temp_install_dir
  changed_when: false

- name: download conda installer
  get_url:
    url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    mode: 0774
    dest: "{{ temp_install_dir.path }}/conda_install.sh"

- name: calculate hashsum of installer
  stat:
    path: "{{ temp_install_dir.path }}/conda_install.sh"
    checksum_algorithm: sha256
  register: st

- fail:
    msg: "Checksum is not right!"
  when: st.stat.checksum != '957d2f0f0701c3d1335e3b39f235d197837ad69a944fa6f5d8ad2c686b69df3b'

- name: run conda installer
  shell: "{{ temp_install_dir.path }}/conda_install.sh -b -p {{ conda_user_home }}/conda3"
  args:
    executable: /bin/bash
    creates: "{{ conda_user_home }}/conda3"

- name: remove temporary installation directory
  file:
    path: "{{ temp_install_dir.path }}"
    state: absent
  changed_when: false
