---
- name: set variables
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - '{{ ansible_os_family }}.yml'
        - default.yml
      paths:
        - 'vars'

- name: Get conda_user home
  become: yes
  getent:
    database: passwd
    key: "{{ conda_user }}"
    split: ":"

- name: set conda user home
  set_fact:
    conda_user_home: "{{ getent_passwd[conda_user][4] }}"

- name: set conda user shell
  set_fact:
    conda_user_shell: "{{ getent_passwd[conda_user][5] }}"

- name: Install conda system requirements
  become: true
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ conda_packages }}"

- name: check if conda3 folder already exists
  stat:
    path: "{{ ansible_env.USER }}/conda3"
  register: conda_result

- name: Install conda
  include_tasks: install-conda.yml
  when: (force_conda_reinstall) or (not conda_result.stat.exists)


- name: install pypi packages
  shell: pip install "{{ item }}"
  environment:
    PATH: "{{ conda_user_home }}/conda3/bin:{{ ansible_env.PATH }}"
  loop: "{{ pypi_packages }}"
