---
ubuntu_repos:
  - 'ppa:nextcloud-devs/client'
  - 'deb http://apt.llvm.org/{{ ansible_distribution_release }}/ llvm-toolchain-{{ ansible_distribution_release}} main'
  - 'deb-src http://apt.llvm.org/{{ ansible_distribution_release }}/ llvm-toolchain-{{ ansible_distribution_release}} main'

suse_repos:
  - 'https://download.opensuse.org/repositories/X11:XOrg/openSUSE_Tumbleweed/X11:XOrg.repo'
  - 'https://download.opensuse.org/repositories/graphics/openSUSE_Tumbleweed/graphics.repo'


common_packages:
  - git
  - thunderbird
  - i3
  - i3status
  - py3status
  - gcc
  - make
  - nextcloud-desktop

ubuntu_packages:
  - build-essential
  - emacsen-common
  - openssh-client
  - systemctl

suse_packages:
  - anki # don't want to use nixGL for now
  - clang
  - systemd
  - borgmatic
  - xf86-video-intel
  - libavcodec56
  - libavcodec57
  - libavcodec58
  - libavformat56
  - libavformat57
  - libavformat58
  - libavdevice56
  - libavdevice57
  - libavdevice58
  - seahorse
  - gnome-keyring
  - libgnome-keyring

suse_patterns:
  - devel_basis

llvm_tools:
  - clang
