{ pkgs, ... }:

let helper = import ./helper.nix;
in (with helper; {
  imports = [ ./fonts.nix ./communication.nix ];

  home.packages = (with pkgs; [
    arandr
    autorandr

    feh
    zathura
    libsForQt5.okular

    redshift
    keepassxc # TODO: is this really desktop module?
    vlc
    spotify

    i3status
    polybarFull
    playerctl

    borgbackup

    # these have all xorg / xauth problems
    # xorg.xbacklight
    # xorg.xhost
    # xorg.xauth
    # or qt problems
    # virtualbox
    # qpdfview
    # libsForQt5.vlc
    # calibre

  ]);

  programs.urxvt = {
    enable = true;
    fonts = [ "xft:iosevkanerdfontmono:size=12:hinting=true:antialias=true" ];
    extraConfig = {
      boldFont =
        "xft:iosevkanerdfontmono:size=12:hinting=true:antialias=true:style=Bold";
      italicFont =
        "xft:iosevkanerdfontmono:size=12:hinting=true:antialias=true:style=Italic";
      boldItalicFont =
        "xft:iosevkanerdfontmono:size=12:hinting=true:antialias=true:style=Bold Italic";
      letterSpace = 0;
      lineSpace = 0;
      geometry = "92x42";
      internalBorder = 24;
      cursorBlink = true;
      cursorUnderline = false;
      urgentOnBell = true;
      depth = 24;
      loginShell = true;
      secondaryScroll = true;

    };
  };
  programs.rofi.enable = true;

  home.file = {
    ".xinputrc".text = ''
      run_im none

      set bell-style none
    '';

    ".xsession".text = ''
      #!/bin/sh
      /bin/sh /home/ben/.xsession-hm
    '';

  };

  xdg = {
    enable = true;
    configFile = {
      "polybar".source = (resolveConfigLocation "polybar");
      "zathura".source = (resolveConfigLocation "zathura");
      "i3status".source = (resolveConfigLocation "i3status");
      "picom".source = (resolveConfigLocation "picom");
    };

  };

  xresources.extraConfig = ''
    rofi.combi-modi:    window,drun,ssh
    rofi.font:          Iosevka 12
    rofi.modi:          combi
    rofi.fuzzy:         true

    ! special
    *.foreground:   #d2c5bc
    *.background:   #101010
    *.cursorColor:  #d2c5bc

    ! black
    *.color0:       #202020
    *.color8:       #2c2c2c

    ! red
    *.color1:       #b91e2e
    *.color9:       #d14548

    ! green
    *.color2:       #81957c
    *.color10:      #a7b79a

    ! yellow
    *.color3:       #f9bb80
    *.color11:      #fae3a0

    ! blue
    *.color4:       #356579
    *.color12:      #7491a1

    ! magenta
    *.color5:       #2d2031
    *.color13:      #87314e

    ! cyan
    *.color6:       #268ad3
    *.color14:      #0f829d

    ! white
    *.color7:       #909090
    *.color15:      #fff0f0

    ! perl extensions
    URxvt.perl-ext-common: default,matcher,font-size
    URxvt.urlLauncher: firefox
    URxvt.keysym.C-S-Up:   font-size:incglobal
    URxvt.keysym.C-S-Down: font-size:decglobal
    URxvt.keysym.C-slash:  font-size:show
  '';

  services = {
    # nextcloud-client.enable = true;
    redshift = {
      enable = true;
      temperature = {
        day = 6000;
        night = 2000;
      };
      provider = "manual";
      latitude = "48";
      longitude = "11";
    };

    flameshot.enable = true;
    gnome-keyring.enable = true;
    network-manager-applet.enable = true;
  };

  # use i3 as wm
  xsession = {
    enable = true;
    scriptPath = ".xsession-hm";
    windowManager.i3 = {
      enable = true;
      config.bars = [ ];
      extraConfig = ''
        # This file has been auto-generated by i3-config-wizard(1).
        # It will not be overwritten, so edit it as you like.
        #
        # Should you change your keyboard layout some time, delete
        # this file and re-run i3-config-wizard(1).
        #

        # i3 config file (v4)
        #
        # Please see https://i3wm.org/docs/userguide.html for a complete reference!

        set $mod Mod4

        set_from_resource $file_viewer i3.file_viewer dolphin

        # Font for window titles. Will also be used by the bar unless a different font
        # is used in the bar {} block below.
        font pango:Iosevka 10

        # This font is widely installed, provides lots of unicode glyphs, right-to-left
        # text rendering and scalability on retina/hidpi displays (thanks to pango).
        #font pango:DejaVu Sans Mono 8

        # Before i3 v4.8, we used to recommend this one as the default:
        # font -misc-fixed-medium-r-normal--13-120-75-75-C-70-iso10646-1
        # The font above is very space-efficient, that is, it looks good, sharp and
        # clear in small sizes. However, its unicode glyph coverage is limited, the old
        # X core fonts rendering does not support right-to-left and this being a bitmap
        # font, it doesn’t scale on retina/hidpi displays.

        # Use Mouse+$mod to drag floating windows to their wanted position
        floating_modifier $mod

        # start a terminal
        bindsym $mod+Return exec i3-sensible-terminal

        # start file viewer
        bindsym $mod+Shift+Return exec --no-startup-id $file_viewer

        # kill focused window
        bindsym $mod+q kill

        # Make the currently focused window a scratchpad
        bindsym $mod+Shift+minus move scratchpad

        # Show the first scratchpad window
        bindsym $mod+minus scratchpad show

        # start rofi (a program launcher)
        bindsym $mod+d exec rofi -show run
        bindsym $mod+c exec rofi -show combi
        bindsym $mod+g exec rofi -show window
        # There also is the (new) i3-dmenu-desktop which only displays applications
        # shipping a .desktop file. It is a wrapper around dmenu, so you need that
        # installed.
        # bindsym $mod+d exec --no-startup-id i3-dmenu-desktop

        # change focus
        bindsym $mod+j focus up
        bindsym $mod+k focus down
        bindsym $mod+l focus right
        bindsym $mod+h focus left
        # bindsym $mod+odiaeresis focus right

        # alternatively, you can use the cursor keys:
        bindsym $mod+Left focus left
        bindsym $mod+Down focus down
        bindsym $mod+Up focus up
        bindsym $mod+Right focus right

        # move focused window
        bindsym $mod+Shift+h move left
        bindsym $mod+Shift+k move down
        bindsym $mod+Shift+j move up
        bindsym $mod+Shift+l move right


        # alternatively, you can use the cursor keys:
        # bindsym $mod+Shift+Left move left
        # bindsym $mod+Shift+Down move down
        # bindsym $mod+Shift+Up move up
        # bindsym $mod+Shift+Right move right

        # split in horizontal orientation
        # bindsym $mod+Shift+h split h

        # split in vertical orientation
        # bindsym $mod+v split v

        # enter fullscreen mode for the focused container
        bindsym $mod+z fullscreen toggle

        # change container layout (stacked, tabbed, toggle split)
        bindsym $mod+s layout stacking
        bindsym $mod+w layout tabbed
        bindsym $mod+e layout toggle split

        # toggle tiling / floating
        bindsym $mod+Shift+space floating toggle

        # change focus between tiling / floating windows
        bindsym $mod+space focus mode_toggle

        # focus the parent container
        bindsym $mod+a focus parent
        focus_follows_mouse no
        # focus the child container
        #bindsym $mod+d focus child

        # Define names for default workspaces for which we configure key bindings later on.
        # We use variables to avoid repeating the names in multiple places.
        set $ws1 "1"
        set $ws2 "2"
        set $ws3 "3"
        set $ws4 "4"
        set $ws5 "5"
        set $ws6 "6"
        set $ws7 "7"
        set $ws8 "8"
        set $ws9 "9"
        set $ws10 "10"

        # switch to workspace
        bindsym $mod+1 workspace $ws1
        bindsym $mod+2 workspace $ws2
        bindsym $mod+3 workspace $ws3
        bindsym $mod+4 workspace $ws4
        bindsym $mod+5 workspace $ws5
        bindsym $mod+6 workspace $ws6
        bindsym $mod+7 workspace $ws7
        bindsym $mod+8 workspace $ws8
        bindsym $mod+9 workspace $ws9
        bindsym $mod+0 workspace $ws10

        # bind to monitors
        set $m1 "eDP1"
        set $m2 "HDMI1"
        workspace $ws1 output $m1
        workspace $ws2 output $m2
        workspace $ws3 output $m2
        workspace $ws4 output $m2
        workspace $ws5 output $m2
        workspace $ws6 output $m2
        workspace $ws7 output $m2
        workspace $ws8 output $m2
        workspace $ws9 output $m2

        bindsym $mod+Shift+Left move workspace to output left
        bindsym $mod+Shift+Right move workspace to output right

        # move focused container to workspace
        bindsym $mod+Shift+1 move container to workspace $ws1
        bindsym $mod+Shift+2 move container to workspace $ws2
        bindsym $mod+Shift+3 move container to workspace $ws3
        bindsym $mod+Shift+4 move container to workspace $ws4
        bindsym $mod+Shift+5 move container to workspace $ws5
        bindsym $mod+Shift+6 move container to workspace $ws6
        bindsym $mod+Shift+7 move container to workspace $ws7
        bindsym $mod+Shift+8 move container to workspace $ws8
        bindsym $mod+Shift+9 move container to workspace $ws9
        bindsym $mod+Shift+0 move container to workspace $ws10

        # reload the configuration file
        bindsym $mod+Shift+c reload
        # restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
        bindsym $mod+Shift+r restart
        # exit i3 (logs you out of your X session)
        bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -B 'Yes, exit i3' 'i3-msg exit'"

        # resize window (you can also use the mouse for that)
        mode "resize" {
                # These bindings trigger as soon as you enter the resize mode

                # Pressing left will shrink the window’s width.
                # Pressing right will grow the window’s width.
                # Pressing up will shrink the window’s height.
                # Pressing down will grow the window’s height.
                bindsym j resize shrink width 10 px or 10 ppt
                bindsym k resize grow height 10 px or 10 ppt
                bindsym l resize shrink height 10 px or 10 ppt
                bindsym odiaeresis resize grow width 10 px or 10 ppt

                # same bindings, but for the arrow keys
                bindsym Left resize shrink width 10 px or 10 ppt
                bindsym Down resize grow height 10 px or 10 ppt
                bindsym Up resize shrink height 10 px or 10 ppt
                bindsym Right resize grow width 10 px or 10 ppt

                # back to normal: Enter or Escape or $mod+r
                bindsym Return mode "default"
                bindsym Escape mode "default"
                bindsym $mod+r mode "default"
        }

        bindsym $mod+r mode "resize"

        # Start i3bar to display a workspace bar (plus the system information i3status
        # finds out, if available)
        bar {
        		position top
                status_command py3status
        }

        floating_modifier $mod

        # volume
        bindsym $mod+u exec amixer -D pulse -q sset Master 5%+ unmute
        bindsym $mod+i exec amixer -D pulse -q sset Master 5%- unmute
        bindsym $mod+o exec amixer -D pulse -q sset Master 1+ toggle
        bindsym XF86AudioLowerVolume exec amixer -D pulse -q sset Master 5%- unmute
        bindsym XF86AudioRaiseVolume exec amixer -D pulse -q sset Master 5%+ unmute
        bindsym XF86AudioMute exec amixer -D pulse -q sset Master 1+ toggle


        # playerctl to play,bindsym XF86AudioPlay exec playerctl play
        bindsym XF86AudioPause exec "playerctl --player=spotify,%any pause"
        bindsym XF86AudioNext exec "playerctl --player=spotify,%any next"
        bindsym XF86AudioPrev exec "playerctl --player=spotify,%any previous"
        bindsym $mod+n exec "playerctl --player=spotify,%any next"
        bindsym $mod+m exec "playerctl --player=spotify,%any previous"
        bindsym $mod+comma exec "playerctl --player=spotify,%any play-pause"


        # Sreen brightness controls
        bindsym $mod+Shift+u exec xbacklight -inc 10 # increase screen brightness
        bindsym $mod+Shift+i exec xbacklight -dec 10 # decrease screen brightness

        # TODO: figure this out
        # exec --no-startup-id compton

        # power on bluetooth
        exec --no-startup-id bluetoothctl power on

        set $i3lock-custom i3lock -c 191970


        set $mode_system System (l) lock, (e) logout, (s) suspend, (r) reboot, (p) shutdown, (k) kill open windows
        mode "$mode_system" {
            bindsym l exec --no-startup-id $i3lock-custom, mode "default"
            bindsym e exec --no-startup-id i3-msg exit, mode "default"
            bindsym s exec --no-startup-id $i3lock-custom && systemctl suspend, mode "default"
            bindsym r exec --no-startup-id systemctl reboot, mode "default"
            bindsym p exec --no-startup-id  systemctl poweroff, mode "default"
        	bindsym k [class=".*"] kill

            # back to normal: Enter or Escape
            bindsym Return mode "default"
            bindsym Escape mode "default"
        }
        bindsym $mod+p mode "$mode_system"


        # background and light
        exec --no-startup-id feh --bg-fill ~/Pictures/Wallpapers/Firefox_wallpaper.png

        assign [class="qpdfview"] $ws1
        assign [class="Emacs"] $ws3
        assign [class="Firefox"] $ws4
        assign [class="Navigator"] $ws4
        assign [class="Thunderbird.*"] $ws5


        exec --no-startup-id qpdfview --unique
        exec --no-startup-id i3-msg 'workspace 2; exec /usr/bin/urxvt -e "tmux"'
        exec --no-startup-id emacs
        exec --no-startup-id firefox
        exec --no-startup-id thunderbird
        exec --no-startup-id spotify
        exec --no-startup-id nextcloud
        exec --no-startup-id nm-applet

        for_window [title=".*\(Private Browsing\).*"] move to workspace "private"
        for_window [class=".*(?i)Spotify.*"] move to workspace "spotify"
        for_window [class="nextcloud"] move scratchpad
        for_window [class="xconsole"] move scratchpad
        for_window [class=".*(?i)signal.*"] move to workspace "signal"
        for_window [class=".*(?i)anki.*"] move to workspace "anki"


        # temp
        bindsym $mod+F1 workspace "anki"
        bindsym $mod+F2 workspace "signal"
        bindsym $mod+F3 workspace "spotify"
        bindsym $mod+F4 workspace "private"
      '';
    };
  };
  # services.screen-locker.lockCmd = "${pkgs.i3lock-fancy}/bin/i3lock-fancy -p -t ''";

  #   services.polybar = {
  #     enable = false;
  #     config = {
  #       "bar/bar" = {
  #         monitor = "\${env:MONITOR:}";
  #         width = "100%";
  #         height = "3%";
  #         radius = 0;
  #         modules-center = "date";
  #       };

  #       "module/date" = {
  #         type = "internal/date";
  #         internal = 5;
  #         date = "%d.%m.%y";
  #         time = "%H:%M";
  #         label = "%time%  %date%";
  #       };

  #     };
  #     script =  ''
  # # for m in $(polybar --list-monitors | cut -d":" -f1); do
  # #     MONITOR=$m polybar --reload example &
  # # done
  # # '';
  #   };

})
