---
- name: create temporary install directory
  tempfile:
    state: directory
    suffix: .install
  register: temp_install_dir
  changed_when: false

- name: get nix install script
  get_url:
    url: https://nixos.org/nix/install
    mode: 0774
    dest: "{{ temp_install_dir.path }}/nix_install.sh"

- name: delete old nix installation
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/profile/nix.sh
    - /etc/profile.d/nix.sh
    - /etc/profile.d/nix.sh.backup-before-nix
    - /etc/nix
    - /nix
    - ~root/.nix-profile
    - ~root/.nix-defexpr
    - ~root/.nix-channels
    - "{{ ansible_env.HOME }}/.nix-profile"
    - "{{ ansible_env.HOME }}/.nix-defexpr"
    - "{{ ansible_env.HOME }}/.nix-channels"
  become: yes
  when: force_nix_reinstall

- name: stop and remove nix-daemon
  shell: |
    set -o pipefail
    systemctl stop nix-daemon.socket
    systemctl stop nix-daemon.service
    systemctl disable nix-daemon.socket
    systemctl disable nix-daemon.service
    systemctl daemon-reload
  args:
    executable: /bin/bash
  when: force_nix_reinstall
  become: yes

- name: execute nix install script
  shell: "{{ temp_install_dir.path }}/nix_install.sh --daemon"
  args:
    creates: /nix

- name: Run the Nix daemon
  become: yes
  service:
    name: nix-daemon
    state: restarted
    enabled: yes

- name: add unstable pkgs channel
  shell: "nix-channel --add https://nixos.org/channels/nixpkgs-unstable"
  environment:
    PATH: "/nix/var/nix/profiles/default/bin:{{ ansible_env.HOME }}/.nix-profile/bin:{{ ansible_env.PATH}}"
