---
- set_fact:
    xdg_data_home: "{{ lookup('env', 'XDG_DATA_HOME') | default(ansible_user_dir ~ '/.local/share', true) }}"

- set_fact:
    font_dir: "{{ xdg_data_home }}/fonts"

- name: make sure fonts folder exists
  file:
    path: "{{ font_dir }}"
    state: directory

- name: download and unpack fonts
  unarchive:
    src: "{{ item }}"
    dest: "{{ font_dir }}"
    list_files: yes
    remote_src: yes
  loop: "{{ fonts_to_download}}"

- name: run fc-cache
  shell: fc-cache
